apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: asteroids-frontend
  name: asteroids-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: asteroids-frontend
  template:
    metadata:
      labels:
        app: asteroids-frontend
    spec:
      containers:
      - name: asteroids-frontend
        image: registry.tino.sh/asteroids-frontend
        resources:
          requests:
            memory: "50Mi"
            cpu: "30m"
          limits:
            memory: "64Mi"
            cpu: "100m"
