apiVersion: v1
kind: Service
metadata:
  labels:
    app: asteroids-frontend-service
  name: asteroids-frontend-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: asteroids-frontend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: asteroids-backend-service
  name: asteroids-backend-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: asteroids-backend

